name: create-compute

on: 
   workflow_dispatch:
   
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:       
        file_name: config-infra-prod.yml  
  create-compute:
    needs: get-config
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v2        
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
      - name: install-extension
        run:  az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml       
      - name: create-compute-default-tier
        run: |
          az ml compute create --name cpu-cluster \
                                  --type AmlCompute \
                                  --tier "dedicated" \
                                  --size Standard_DS3_v2 \
                                  --min-instances 0 \
                                  --max-instances 4 \
                                  --resource-group ${{ needs.get-config.outputs.resource_group }} \
                                  --workspace-name ${{ needs.get-config.outputs.aml_workspace }}  
      
