name: register-dataset

on:
  workflow_dispatch:
  
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        #environment_file:  mlops/azureml/train/train-env.yml
        #conda_file: data-science/environment/train-conda.yml
        file_name: config-infra-prod.yml  
  register-dataset:
    needs: get-config
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: create-dataset-from-file      
        run: |
          az ml data create --file ${{ github.workspace }}/mlops/azureml/train/data.yml --resource-group ${{ needs.get-config.outputs.resource_group }} \
          --workspace-name ${{ needs.get-config.outputs.aml_workspace }} --name taxi-data
      
